[package]
name = "wallet-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari", branch = "development" }
tari_utilities = { version = "0.8" }


