[package]
name = "wallet-decoder"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari", branch = "development" }
tari_utilities = { version = "0.8" }
tari_crypto = { version = "0.22" }
tari_key_manager = { git = "https://github.com/tari-project/tari", branch = "development", features = ["key_manager_service"] }
tari_core = { git = "https://github.com/tari-project/tari", branch = "development" }
tari_common = { git = "https://github.com/tari-project/tari", branch = "development" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
rand_chacha = "0.3"
zeroize = "1.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }


