[package]
name = "wallet-decoder"
version = "0.1.6"
edition = "2024"
authors = ["Krakaw"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari", branch = "development"}
tari_utilities = { version = "0.8", default-features = false }
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
anyhow = "1.0"
bs58 = "0.5.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari", branch = "development"}
tari_utilities = { version = "0.8", default-features = false }
tari_key_manager = { git = "https://github.com/tari-project/tari", branch = "development" }
tari_core = { git = "https://github.com/tari-project/tari", branch = "development" }
tari_common = { git = "https://github.com/tari-project/tari", branch = "development" }
clap = { version = "4.4", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"


