// This file is automatically generated by tonic_build.
// Please do not edit it manually.
// It will be populated when build.rs runs successfully.

// Example of what might be generated (actual content will vary):
// pub mod tari {
//     pub mod rpc {
//         // tonic::include_proto!("tari.rpc"); // This is a common pattern
//         // but since we are outputting directly to src, specific modules will be here.
//     }
// }
// We will inspect this file after the first successful build.
// For now, it can be empty or contain a comment.
