name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          echo "Building WASM module..."
          wasm-pack build --target web --verbose
          echo "Checking pkg directory contents..."
          ls -la pkg/
          echo "Copying index.html..."
          cp index.html pkg/
          echo "Creating _redirects file..."
          echo '{
            "rewrites": [
              { "source": "**", "destination": "/index.html" }
            ]
          }' > pkg/_redirects
          echo "Final pkg directory contents:"
          ls -la pkg/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pkg
          branch: gh-pages
          clean: true
          commit-message: "Deploy WASM module and web interface" 