name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wallet-decoder-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/wallet-decoder
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: |
          echo "Contents of artifacts directory:"
          ls -la artifacts/
          echo "Contents of artifacts subdirectories:"
          find artifacts -type f

      - name: Prepare release files
        run: |
          mkdir -p release
          cp artifacts/wallet-decoder-aarch64-apple-darwin release/wallet-decoder-aarch64-apple-darwin
          cp artifacts/wallet-decoder-x86_64-unknown-linux-gnu release/wallet-decoder-x86_64-unknown-linux-gnu

      - name: List release files
        run: ls -la release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            release/wallet-decoder-aarch64-apple-darwin
            release/wallet-decoder-x86_64-unknown-linux-gnu
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 